#!/bin/bash

FILES=( $(git status --porcelain | grep ^M) );
V=$(date -u +%Y-%m-%d);

n=1;
while [ "$n" -lt "${#FILES[@]}" ]; do
  case "${FILES[$n]}" in
    "run_parallel.inc.sh" )
      [ "${FILES[$((n-1))]}" == "MM" ] &&
        echo "${0##*/}: error: unable to update version due to change after staged: ${FILES[$n]}" 1>&2 &&
        exit 1;
      echo "${0##*/}: updating version of ${FILES[$n]}" 1>&2;
      sed -i 's|$Version:[^$]*\$|$Version: '"$V"'$|' "${FILES[$n]}";
      git add "${FILES[$n]}";
      { . run_parallel.inc.sh;
        run_parallel --markdown;
        printf "# COPYRIGHT\n\n";
        sed -n '/MIT License/,/^$/{ s|^## *||; p; }' run_parallel.inc.sh;
      } > README.md;
      git add README.md;
      ;;
  esac
  if [ "${FILES[$n]:$((${#FILES[$n]}-3))}" = ".sh" ]; then
    echo "${0##*/}: checking syntax of ${FILES[$n]}" 1>&2;
    bash -n "${FILES[$n]}";
  fi
  [ "$?" != "0" ] && exit 1;
  n=$((n+2));
done

exit 0;
